baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '尹宇'
theme = 'ananke'
publishDir = "docs"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true